---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: fifo

generatorOptions:
  disableNameSuffixHash: true

resources:
  - aws-load-balancer-controller.yaml
  - aws-load-balancer-ingress.yaml
