---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This feature was introduced in Kustomization 5.0 to control order
sortOptions:
  order: fifo

generatorOptions:
  disableNameSuffixHash: false

resources:
  - certmanager.yaml
  - cluster-issuer.yaml
  - cert-manager-service-account.yaml
  - custom-subdomain-certificate.yaml
  - ingress-controller.yaml
