apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: automation-hub-s3-secret
  namespace: external-secrets
spec:
  externalSecretName: "automation-hub-s3-secret"  
  namespaceSelector:
    matchLabels: 
      kubernetes.io/metadata.name: ansible-automation-platform
  refreshTime: 1m
  externalSecretSpec:
    refreshInterval: 1m
    secretStoreRef:
      name: cluster-secret-store
      kind: ClusterSecretStore
    target:
      name: automation-hub-s3-secret
      template:
        type: Opaque
        data:
          s3-access-key-id: "False"
          s3-bucket-name: "{{ .s3_bucket_name }}"
          s3-region: "{{ .s3_region }}"
          s3-secret-access-key: "False"
    data:
    - secretKey: s3_region
      remoteRef:
        key: "${CLUSTER_NAME}"
        property: REGION
    - secretKey: s3_bucket_name
      remoteRef:
        key: "${CLUSTER_NAME}"
        property: S3_BUCKET