apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: automation-controller-ee-pull-credentials
  namespace: external-secrets
spec:
  externalSecretName: "automation-controller-ee-pull-credentials"
  namespaceSelector:
    matchLabels: 
      kubernetes.io/metadata.name: ansible-automation-platform
  refreshTime: 1m
  externalSecretSpec:
    refreshInterval: 1m
    secretStoreRef:
      name: cluster-cross-account-secret-store
      kind: ClusterSecretStore
    target:
      name: automation-controller-ee-pull-credentials
      template:
        type: Opaque
        data:
          password: "{{ .token }}"
          url: 'registry.redhat.io'
          username: "{{ .username}}"
    data:
    - secretKey: username
      remoteRef:
        key: "redhat-registry-image-pull-secret"
        property: username
    - secretKey: token
      remoteRef:
        key: "redhat-registry-image-pull-secret"
        property: token
