apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: automation-hub-admin-password
  namespace: external-secrets
spec:
  externalSecretName: "automation-hub-admin-password"  
  namespaceSelector:
    matchLabels: 
      kubernetes.io/metadata.name: ansible-automation-platform
  refreshTime: 1m
  externalSecretSpec:
    refreshInterval: 1m
    secretStoreRef:
      name: cluster-secret-store
      kind: ClusterSecretStore
    target:
      name: automation-hub-admin-password
      template:
        type: Opaque
        data:
          password: "{{ .password }}"
    data:
    - secretKey: password
      remoteRef:
        key: "${CLUSTER_NAME}-aap-credentials"