---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: fifo

generatorOptions:
  disableNameSuffixHash: false

resources:
  - resources

secretGenerator:
  - name: rds-init-db-configuration
    namespace: ansible-automation-platform
    files:
      - secrets.env

